### ISSUE TITLE
Missing tailrec doc at cheatsheet

### ISSUE THREAD

**Issue by ezequielmasciarelli** [riiswa/Scala-CheatSheet#1]
Hey dude I Love your Scala cheatsheet!
As a sugestion you can add an example of a simple factorial using the traditional and tailrecursive form.
Ex:
  def factorial(n:Int):Int = {
    if(n==1) 1
    else n * factorial(n-1)
  }

//Pushes N Times into the JVM stack

  def factorial2(n:Int):Int ={
    @tailrec
    def factorial2Helper(act:Int,acc:Int):Int = {
      if(act==1) acc
      else factorial2Helper(act-1,acc * act)
    }
    factorial2Helper(n,1)
  }
//Only pushes one time into the stack

**Comment by riiswa** [comment]
Thank you for your idea! I will update my cheat sheet with your suggestions
